### ISSUE TITLE
You do not need freestanding C++ headers any more since GCC 12

### ISSUE THREAD

**Issue by trcrsired** [mintsuki/freestanding-cxx-hdrs#1]
libstdc++ has already supported freestanding without issues.
GCC 13 or GCC 14 are even better.

**Comment by mintsuki** [comment]
I don't see the point of this issue since the whole point of this repository is to provide standalone headers usable with `-nostdinc` and compilers that aren't GCC (namely Clang) and with GCC versions older than 12.
